[2023-12-07 20:12:19,477: INFO: main: welcome to custom Log]
[2023-12-11 20:54:07,579: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-12-11 20:54:07,579: ERROR: main: DataIngestionTrainingPipeline.main() takes 0 positional arguments but 1 was given]
Traceback (most recent call last):
  File "E:\mlops\Kidney-Disease-Classification-DL-Project\main.py", line 11, in <module>
    data_ingestion.main()
TypeError: DataIngestionTrainingPipeline.main() takes 0 positional arguments but 1 was given
[2023-12-11 20:55:57,417: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-12-11 20:55:57,418: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-11 20:55:57,419: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-11 20:55:57,420: INFO: common: created directory at: artifacts]
[2023-12-11 20:55:57,420: INFO: common: created directory at: artifacts/data_ingestion]
[2023-12-11 20:55:57,421: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2023-12-11 20:56:10,093: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2023-12-11 20:56:10,731: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2023-12-12 20:36:36,363: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-12-12 20:36:36,364: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-12 20:36:36,370: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-12 20:36:36,370: INFO: common: created directory at: artifacts]
[2023-12-12 20:36:36,371: INFO: common: created directory at: artifacts/data_ingestion]
[2023-12-12 20:36:36,371: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2023-12-12 20:36:45,519: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2023-12-12 20:36:46,045: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2023-12-12 20:36:46,045: INFO: main: =====================##########=============================]
[2023-12-12 20:36:46,045: INFO: main: >>>>>> stage Prepare Base Model started <<<<<<]
[2023-12-12 20:36:46,047: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-12 20:36:46,048: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-12 20:36:46,048: INFO: common: created directory at: artifacts]
[2023-12-12 20:36:46,049: INFO: common: created directory at: artifacts/prepare_base_model]
[2023-12-12 20:36:46,499: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2023-12-12 20:36:46,661: INFO: main: >>>>>> stage Prepare Base Model completed <<<<<<

x==========x]
[2023-12-15 19:23:35,492: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-15 19:23:35,519: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-15 19:23:35,524: INFO: common: created directory at: artifacts]
[2023-12-15 19:23:35,528: INFO: common: created directory at: artifacts\training]
[2023-12-15 20:00:05,200: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-12-15 20:00:05,201: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-15 20:00:05,207: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-15 20:00:05,207: INFO: common: created directory at: artifacts]
[2023-12-15 20:00:05,207: ERROR: main: 'ConfigurationManager' object has no attribute 'get_data_ingestion_config']
Traceback (most recent call last):
  File "E:\mlops\Kidney-Disease-Classification-DL-Project\main.py", line 13, in <module>
    data_ingestion.main()
  File "E:\mlops\Kidney-Disease-Classification-DL-Project\src\cnnClassifier\pipeline\Stage_01_data_ingestion.py", line 13, in main
    data_ingestion_config = config.get_data_ingestion_config()
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigurationManager' object has no attribute 'get_data_ingestion_config'
[2023-12-15 20:03:48,034: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-12-15 20:03:48,036: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-15 20:03:48,037: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-15 20:03:48,037: INFO: common: created directory at: artifacts]
[2023-12-15 20:03:48,037: ERROR: main: 'ConfigurationManager' object has no attribute 'get_data_ingestion_config']
Traceback (most recent call last):
  File "E:\mlops\Kidney-Disease-Classification-DL-Project\main.py", line 13, in <module>
    data_ingestion.main()
  File "E:\mlops\Kidney-Disease-Classification-DL-Project\src\cnnClassifier\pipeline\Stage_01_data_ingestion.py", line 13, in main
    data_ingestion_config = config.get_data_ingestion_config()
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigurationManager' object has no attribute 'get_data_ingestion_config'
[2023-12-15 20:05:34,451: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-12-15 20:05:34,452: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-15 20:05:34,453: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-15 20:05:34,454: INFO: common: created directory at: artifacts]
[2023-12-15 20:05:34,454: INFO: common: created directory at: artifacts/data_ingestion]
[2023-12-15 20:05:34,455: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2023-12-15 20:05:45,053: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2023-12-15 20:05:45,571: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2023-12-15 20:05:45,571: INFO: main: =====================##########=============================]
[2023-12-15 20:05:45,571: INFO: main: >>>>>> stage Prepare Base Model started <<<<<<]
[2023-12-15 20:05:45,572: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-15 20:05:45,573: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-15 20:05:45,574: INFO: common: created directory at: artifacts]
[2023-12-15 20:05:45,574: INFO: common: created directory at: artifacts/prepare_base_model]
[2023-12-15 20:05:45,938: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2023-12-15 20:05:46,132: INFO: main: >>>>>> stage Prepare Base Model completed <<<<<<

x==========x]
[2023-12-15 20:05:46,132: INFO: main: =====================##########=============================]
[2023-12-15 20:05:46,132: INFO: main: >>>>>> stage Training started <<<<<<]
[2023-12-15 20:05:46,133: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-15 20:05:46,134: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-15 20:05:46,135: INFO: common: created directory at: artifacts]
[2023-12-15 20:05:46,135: INFO: common: created directory at: artifacts\training]
[2023-12-15 20:21:42,226: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2023-12-16 20:23:50,960: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-16 20:23:50,963: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-16 20:23:50,963: INFO: common: created directory at: artifacts]
[2023-12-16 20:25:39,608: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-16 20:25:39,611: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-16 20:25:39,613: INFO: common: created directory at: artifacts]
[2023-12-16 20:26:39,156: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-16 20:26:39,159: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-16 20:26:39,160: INFO: common: created directory at: artifacts]
[2023-12-16 20:26:52,294: INFO: common: json file saved at: scores.json]
[2023-12-16 20:29:01,901: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-16 20:29:01,904: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-16 20:29:01,906: INFO: common: created directory at: artifacts]
[2023-12-16 20:29:14,278: INFO: common: json file saved at: scores.json]
[2023-12-16 20:30:49,563: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-16 20:30:49,566: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-16 20:30:49,568: INFO: common: created directory at: artifacts]
[2023-12-16 20:31:02,362: INFO: common: json file saved at: scores.json]
[2023-12-16 20:39:19,596: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-16 20:39:19,602: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-16 20:39:19,604: INFO: common: created directory at: artifacts]
[2023-12-16 20:39:32,669: INFO: common: json file saved at: scores.json]
[2023-12-16 21:04:25,323: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-12-16 21:04:25,324: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-16 21:04:25,326: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-16 21:04:25,326: INFO: common: created directory at: artifacts]
[2023-12-16 21:04:25,326: INFO: common: created directory at: artifacts/data_ingestion]
[2023-12-16 21:04:25,327: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2023-12-16 21:04:35,028: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2023-12-16 21:04:35,577: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2023-12-16 21:04:35,577: INFO: main: =====================##########=============================]
[2023-12-16 21:04:35,577: INFO: main: >>>>>> stage Prepare Base Model started <<<<<<]
[2023-12-16 21:04:35,578: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-16 21:04:35,579: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-16 21:04:35,580: INFO: common: created directory at: artifacts]
[2023-12-16 21:04:35,580: INFO: common: created directory at: artifacts/prepare_base_model]
[2023-12-16 21:04:35,977: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2023-12-16 21:04:36,207: INFO: main: >>>>>> stage Prepare Base Model completed <<<<<<

x==========x]
[2023-12-16 21:04:36,207: INFO: main: =====================##########=============================]
[2023-12-16 21:04:36,207: INFO: main: >>>>>> stage Training started <<<<<<]
[2023-12-16 21:04:36,209: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-16 21:04:36,210: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-16 21:04:36,210: INFO: common: created directory at: artifacts]
[2023-12-16 21:04:36,211: INFO: common: created directory at: artifacts\training]
[2023-12-16 21:07:47,888: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2023-12-16 21:40:42,816: INFO: stage_04_model_evaluation: *******************]
[2023-12-16 21:40:42,816: INFO: stage_04_model_evaluation: >>>>>> stage Evaluation stage started <<<<<<]
[2023-12-16 21:40:42,817: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-16 21:40:42,818: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-16 21:40:42,819: INFO: common: created directory at: artifacts]
[2023-12-16 21:40:54,258: INFO: common: json file saved at: scores.json]
[2023-12-16 21:40:54,258: INFO: common: json file saved at: scores.json]
[2023-12-16 21:40:57,309: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2023-12-16 21:40:57,927: INFO: builder_impl: Assets written to: C:\Users\REHANS~1\AppData\Local\Temp\tmpjrsfld9h\model\data\model\assets]
[2023-12-16 21:41:37,323: INFO: stage_04_model_evaluation: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2023-12-16 21:41:37,323: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-12-16 21:41:37,324: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-16 21:41:37,325: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-16 21:41:37,325: INFO: common: created directory at: artifacts]
[2023-12-16 21:41:37,326: INFO: common: created directory at: artifacts/data_ingestion]
[2023-12-16 21:41:37,326: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2023-12-16 21:42:05,823: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2023-12-16 21:42:06,308: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2023-12-16 21:42:06,309: INFO: main: =====================##########=============================]
[2023-12-16 21:42:06,309: INFO: main: >>>>>> stage Prepare Base Model started <<<<<<]
[2023-12-16 21:42:06,310: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-16 21:42:06,311: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-16 21:42:06,311: INFO: common: created directory at: artifacts]
[2023-12-16 21:42:06,312: INFO: common: created directory at: artifacts/prepare_base_model]
[2023-12-16 21:42:06,620: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2023-12-16 21:42:06,775: INFO: main: >>>>>> stage Prepare Base Model completed <<<<<<

x==========x]
[2023-12-16 21:42:06,775: INFO: main: =====================##########=============================]
[2023-12-16 21:42:06,775: INFO: main: >>>>>> stage Training started <<<<<<]
[2023-12-16 21:42:06,776: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-16 21:42:06,777: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-16 21:42:06,778: INFO: common: created directory at: artifacts]
[2023-12-16 21:42:06,778: INFO: common: created directory at: artifacts\training]
[2023-12-16 21:45:11,344: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2023-12-16 21:45:11,344: INFO: main: *******************]
[2023-12-16 21:45:11,344: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2023-12-16 21:45:11,346: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-16 21:45:11,347: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-16 21:45:11,347: INFO: common: created directory at: artifacts]
[2023-12-16 21:45:23,105: INFO: common: json file saved at: scores.json]
[2023-12-16 21:45:23,106: INFO: common: json file saved at: scores.json]
[2023-12-16 21:45:25,360: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2023-12-16 21:45:25,829: INFO: builder_impl: Assets written to: C:\Users\REHANS~1\AppData\Local\Temp\tmpmfe9m76z\model\data\model\assets]
[2023-12-16 21:45:59,770: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2023-12-16 21:49:17,150: INFO: stage_04_model_evaluation: *******************]
[2023-12-16 21:49:17,151: INFO: stage_04_model_evaluation: >>>>>> stage Evaluation stage started <<<<<<]
[2023-12-16 21:49:17,152: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-16 21:49:17,158: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-16 21:49:17,158: INFO: common: created directory at: artifacts]
[2023-12-16 21:49:28,878: INFO: common: json file saved at: scores.json]
[2023-12-16 21:49:28,879: INFO: common: json file saved at: scores.json]
[2023-12-16 21:49:31,520: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2023-12-16 21:49:32,114: INFO: builder_impl: Assets written to: C:\Users\REHANS~1\AppData\Local\Temp\tmpinqnimyu\model\data\model\assets]
[2023-12-16 21:50:07,210: INFO: stage_04_model_evaluation: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2023-12-16 21:50:07,210: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-12-16 21:50:07,212: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-16 21:50:07,212: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-16 21:50:07,213: INFO: common: created directory at: artifacts]
[2023-12-16 21:50:07,213: INFO: common: created directory at: artifacts/data_ingestion]
[2023-12-16 21:50:07,213: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2023-12-16 21:50:30,473: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2023-12-16 21:50:30,969: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2023-12-16 21:50:30,969: INFO: main: =====================##########=============================]
[2023-12-16 21:50:30,969: INFO: main: >>>>>> stage Prepare Base Model started <<<<<<]
[2023-12-16 21:50:30,971: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-16 21:50:30,971: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-16 21:50:30,972: INFO: common: created directory at: artifacts]
[2023-12-16 21:50:30,972: INFO: common: created directory at: artifacts/prepare_base_model]
[2023-12-16 21:50:31,262: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2023-12-16 21:50:31,415: INFO: main: >>>>>> stage Prepare Base Model completed <<<<<<

x==========x]
[2023-12-16 21:50:31,415: INFO: main: =====================##########=============================]
[2023-12-16 21:50:31,415: INFO: main: >>>>>> stage Training started <<<<<<]
[2023-12-16 21:50:31,417: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-16 21:50:31,418: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-16 21:50:31,418: INFO: common: created directory at: artifacts]
[2023-12-16 21:50:31,418: INFO: common: created directory at: artifacts\training]
[2023-12-16 21:56:45,585: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2023-12-16 21:56:45,585: INFO: main: *******************]
[2023-12-16 21:56:45,585: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2023-12-16 21:56:45,587: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-16 21:56:45,588: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-16 21:56:45,588: INFO: common: created directory at: artifacts]
[2023-12-16 21:56:58,636: INFO: common: json file saved at: scores.json]
[2023-12-16 21:56:58,637: INFO: common: json file saved at: scores.json]
[2023-12-16 21:57:00,994: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2023-12-16 21:57:01,482: INFO: builder_impl: Assets written to: C:\Users\REHANS~1\AppData\Local\Temp\tmpmze58zeg\model\data\model\assets]
[2023-12-16 21:57:36,470: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2023-12-18 21:06:38,995: INFO: stage_04_model_evaluation: *******************]
[2023-12-18 21:06:38,996: INFO: stage_04_model_evaluation: >>>>>> stage Evaluation stage started <<<<<<]
[2023-12-18 21:06:39,002: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-18 21:06:39,008: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-18 21:06:39,008: INFO: common: created directory at: artifacts]
[2023-12-18 21:06:51,810: INFO: common: json file saved at: scores.json]
[2023-12-18 21:06:51,811: INFO: common: json file saved at: scores.json]
[2023-12-18 21:06:55,049: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2023-12-18 21:06:55,557: INFO: builder_impl: Assets written to: C:\Users\REHANS~1\AppData\Local\Temp\tmpgff0tc72\model\data\model\assets]
[2023-12-18 21:07:36,027: INFO: stage_04_model_evaluation: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2023-12-18 21:07:36,027: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-12-18 21:07:36,028: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-18 21:07:36,029: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-18 21:07:36,030: INFO: common: created directory at: artifacts]
[2023-12-18 21:07:36,030: INFO: common: created directory at: artifacts/data_ingestion]
[2023-12-18 21:07:36,030: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2023-12-18 21:07:46,279: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2023-12-18 21:07:46,870: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2023-12-18 21:07:46,870: INFO: main: =====================##########=============================]
[2023-12-18 21:07:46,870: INFO: main: >>>>>> stage Prepare Base Model started <<<<<<]
[2023-12-18 21:07:46,871: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-18 21:07:46,872: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-18 21:07:46,872: INFO: common: created directory at: artifacts]
[2023-12-18 21:07:46,873: INFO: common: created directory at: artifacts/prepare_base_model]
[2023-12-18 21:07:47,213: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2023-12-18 21:07:47,407: INFO: main: >>>>>> stage Prepare Base Model completed <<<<<<

x==========x]
[2023-12-18 21:07:47,407: INFO: main: =====================##########=============================]
[2023-12-18 21:07:47,407: INFO: main: >>>>>> stage Training started <<<<<<]
[2023-12-18 21:07:47,409: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-18 21:07:47,410: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-18 21:07:47,410: INFO: common: created directory at: artifacts]
[2023-12-18 21:07:47,411: INFO: common: created directory at: artifacts\training]
[2023-12-18 21:17:17,647: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2023-12-18 21:17:17,647: INFO: main: *******************]
[2023-12-18 21:17:17,647: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2023-12-18 21:17:17,648: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-18 21:17:17,650: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-18 21:17:17,650: INFO: common: created directory at: artifacts]
[2023-12-18 21:17:29,973: INFO: common: json file saved at: scores.json]
[2023-12-18 21:17:29,974: INFO: common: json file saved at: scores.json]
[2023-12-18 21:17:32,342: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2023-12-18 21:17:32,837: INFO: builder_impl: Assets written to: C:\Users\REHANS~1\AppData\Local\Temp\tmpxyw0x9ji\model\data\model\assets]
[2023-12-18 21:18:06,953: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2023-12-20 18:13:12,624: INFO: Stage_01_data_ingestion: >>>>>> stage Data Ingestion Stage started <<<<<<]
[2023-12-20 18:13:12,626: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-20 18:13:12,628: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-20 18:13:12,629: INFO: common: created directory at: artifacts]
[2023-12-20 18:13:12,630: INFO: common: created directory at: artifacts/data_ingestion]
[2023-12-20 18:13:12,630: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2023-12-20 18:13:21,269: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2023-12-20 18:13:21,970: INFO: Stage_01_data_ingestion: >>>>>> stage Data Ingestion Stage completed <<<<<<

x==========x]
[2023-12-20 18:13:40,210: INFO: stage_02_prepare_base_model: >>>>>> stage Prepare Base Model started <<<<<<]
[2023-12-20 18:13:40,211: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-20 18:13:40,212: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-20 18:13:40,213: INFO: common: created directory at: artifacts]
[2023-12-20 18:13:40,214: INFO: common: created directory at: artifacts/prepare_base_model]
[2023-12-20 18:13:40,686: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2023-12-20 18:13:40,874: INFO: stage_02_prepare_base_model: >>>>>> stage Prepare Base Model completed <<<<<<

x==========x]
[2023-12-20 19:19:17,629: INFO: stage_03_model_training: *******************]
[2023-12-20 19:19:17,630: INFO: stage_03_model_training: >>>>>> stage Training started <<<<<<]
[2023-12-20 19:19:17,632: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-20 19:19:17,633: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-20 19:19:17,634: INFO: common: created directory at: artifacts]
[2023-12-20 19:19:17,634: INFO: common: created directory at: artifacts\training]
[2023-12-20 19:28:51,504: INFO: stage_03_model_training: >>>>>> stage Training completed <<<<<<

x==========x]
[2023-12-20 19:28:59,179: INFO: stage_04_model_evaluation: *******************]
[2023-12-20 19:28:59,180: INFO: stage_04_model_evaluation: >>>>>> stage Evaluation stage started <<<<<<]
[2023-12-20 19:28:59,181: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-20 19:28:59,183: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-20 19:28:59,183: INFO: common: created directory at: artifacts]
[2023-12-20 19:29:11,345: INFO: common: json file saved at: scores.json]
[2023-12-20 19:29:11,346: INFO: common: json file saved at: scores.json]
[2023-12-20 19:29:11,346: INFO: stage_04_model_evaluation: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2023-12-20 19:29:11,346: INFO: stage_04_model_evaluation: *******************]
[2023-12-20 19:29:11,346: INFO: stage_04_model_evaluation: >>>>>> stage Evaluation stage started <<<<<<]
[2023-12-20 19:29:11,348: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-20 19:29:11,349: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-20 19:29:11,350: INFO: common: created directory at: artifacts]
[2023-12-20 19:29:23,668: INFO: common: json file saved at: scores.json]
[2023-12-20 19:29:23,669: INFO: common: json file saved at: scores.json]
[2023-12-20 19:29:23,669: INFO: stage_04_model_evaluation: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2023-12-21 19:54:18,991: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.0.102:8080]
[2023-12-21 19:54:18,992: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2023-12-21 19:54:51,492: INFO: _internal: 127.0.0.1 - - [21/Dec/2023 19:54:51] "GET / HTTP/1.1" 200 -]
[2023-12-21 19:55:23,105: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\Rehan Shaikh\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rehan Shaikh\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rehan Shaikh\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rehan Shaikh\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rehan Shaikh\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rehan Shaikh\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
                         ^^^^^^^^^^^^^^^^^^
  File "E:\mlops\Kidney-Disease-Classification-DL-Project\app.py", line 40, in predictRoute
    result = clApp.classifier.predict()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\mlops\Kidney-Disease-Classification-DL-Project\src\cnnClassifier\pipeline\predict.py", line 16, in predict
    model = load_model(os.path.join("model", "model.h5"))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rehan Shaikh\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\saving\saving_api.py", line 212, in load_model
    return legacy_sm_saving_lib.load_model(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rehan Shaikh\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\Rehan Shaikh\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\saving\legacy\save.py", line 230, in load_model
    raise IOError(
OSError: No file or directory found at model\model.h5
[2023-12-21 19:55:23,117: INFO: _internal: 127.0.0.1 - - [21/Dec/2023 19:55:23] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2023-12-21 20:02:08,717: INFO: _internal: 127.0.0.1 - - [21/Dec/2023 20:02:08] "GET / HTTP/1.1" 200 -]
[2023-12-21 20:02:14,298: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\Rehan Shaikh\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rehan Shaikh\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rehan Shaikh\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rehan Shaikh\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rehan Shaikh\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rehan Shaikh\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
                         ^^^^^^^^^^^^^^^^^^
  File "E:\mlops\Kidney-Disease-Classification-DL-Project\app.py", line 40, in predictRoute
    result = clApp.classifier.predict()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\mlops\Kidney-Disease-Classification-DL-Project\src\cnnClassifier\pipeline\predict.py", line 16, in predict
    # load model
            ^^^^^
  File "C:\Users\Rehan Shaikh\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\saving\saving_api.py", line 212, in load_model
    return legacy_sm_saving_lib.load_model(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rehan Shaikh\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\Rehan Shaikh\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\saving\legacy\save.py", line 230, in load_model
    raise IOError(
OSError: No file or directory found at model\model.h5
[2023-12-21 20:02:14,307: INFO: _internal: 127.0.0.1 - - [21/Dec/2023 20:02:14] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2023-12-21 20:20:49,599: INFO: _internal: 127.0.0.1 - - [21/Dec/2023 20:20:49] "GET / HTTP/1.1" 200 -]
[2023-12-21 20:20:54,289: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\Rehan Shaikh\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rehan Shaikh\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rehan Shaikh\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rehan Shaikh\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rehan Shaikh\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rehan Shaikh\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
                         ^^^^^^^^^^^^^^^^^^
  File "E:\mlops\Kidney-Disease-Classification-DL-Project\app.py", line 40, in predictRoute
    result = clApp.classifier.predict()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\mlops\Kidney-Disease-Classification-DL-Project\src\cnnClassifier\pipeline\predict.py", line 16, in predict
    # load model
            ^^^^^
  File "C:\Users\Rehan Shaikh\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\saving\saving_api.py", line 212, in load_model
    return legacy_sm_saving_lib.load_model(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rehan Shaikh\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\Rehan Shaikh\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\saving\legacy\save.py", line 230, in load_model
    raise IOError(
OSError: No file or directory found at model\model.h5
[2023-12-21 20:20:54,297: INFO: _internal: 127.0.0.1 - - [21/Dec/2023 20:20:54] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2023-12-21 20:22:17,358: INFO: _internal: 127.0.0.1 - - [21/Dec/2023 20:22:17] "GET / HTTP/1.1" 200 -]
[2023-12-21 20:22:40,081: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\Rehan Shaikh\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rehan Shaikh\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rehan Shaikh\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rehan Shaikh\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rehan Shaikh\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rehan Shaikh\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
                         ^^^^^^^^^^^^^^^^^^
  File "E:\mlops\Kidney-Disease-Classification-DL-Project\app.py", line 40, in predictRoute
    result = clApp.classifier.predict()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\mlops\Kidney-Disease-Classification-DL-Project\src\cnnClassifier\pipeline\predict.py", line 16, in predict
    # load model
            ^^^^^
  File "C:\Users\Rehan Shaikh\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\saving\saving_api.py", line 212, in load_model
    return legacy_sm_saving_lib.load_model(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rehan Shaikh\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\Rehan Shaikh\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\saving\legacy\save.py", line 230, in load_model
    raise IOError(
OSError: No file or directory found at model\model.h5
[2023-12-21 20:22:40,089: INFO: _internal: 127.0.0.1 - - [21/Dec/2023 20:22:40] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2023-12-21 20:25:09,736: INFO: _internal: 127.0.0.1 - - [21/Dec/2023 20:25:09] "GET / HTTP/1.1" 200 -]
[2023-12-21 20:25:13,744: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\Rehan Shaikh\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rehan Shaikh\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rehan Shaikh\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rehan Shaikh\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rehan Shaikh\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rehan Shaikh\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
                         ^^^^^^^^^^^^^^^^^^
  File "E:\mlops\Kidney-Disease-Classification-DL-Project\app.py", line 40, in predictRoute
    result = clApp.classifier.predict()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\mlops\Kidney-Disease-Classification-DL-Project\src\cnnClassifier\pipeline\predict.py", line 16, in predict
    # load model
            ^^^^^
  File "C:\Users\Rehan Shaikh\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\saving\saving_api.py", line 212, in load_model
    return legacy_sm_saving_lib.load_model(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rehan Shaikh\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\Rehan Shaikh\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\saving\legacy\save.py", line 230, in load_model
    raise IOError(
OSError: No file or directory found at model\model.h5
[2023-12-21 20:25:13,752: INFO: _internal: 127.0.0.1 - - [21/Dec/2023 20:25:13] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2023-12-21 20:25:27,190: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.0.102:8080]
[2023-12-21 20:25:27,190: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2023-12-21 20:26:30,036: INFO: _internal: 127.0.0.1 - - [21/Dec/2023 20:26:30] "GET / HTTP/1.1" 200 -]
[2023-12-21 20:26:39,418: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\Rehan Shaikh\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rehan Shaikh\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rehan Shaikh\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rehan Shaikh\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rehan Shaikh\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rehan Shaikh\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
                         ^^^^^^^^^^^^^^^^^^
  File "E:\mlops\Kidney-Disease-Classification-DL-Project\app.py", line 40, in predictRoute
    result = clApp.classifier.predict()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\mlops\Kidney-Disease-Classification-DL-Project\src\cnnClassifier\pipeline\predict.py", line 20, in predict
    test_image = image.load_img(imagename, target_size = (224,224))
                 ^^^^^^^^^^^^^^
AttributeError: module 'keras.preprocessing.image' has no attribute 'load_img'
[2023-12-21 20:26:39,421: INFO: _internal: 127.0.0.1 - - [21/Dec/2023 20:26:39] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2023-12-21 20:32:01,991: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.0.102:8080]
[2023-12-21 20:32:01,991: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2023-12-21 20:32:03,627: INFO: _internal: 127.0.0.1 - - [21/Dec/2023 20:32:03] "GET / HTTP/1.1" 200 -]
[2023-12-21 20:32:09,398: INFO: _internal: 127.0.0.1 - - [21/Dec/2023 20:32:09] "POST /predict HTTP/1.1" 200 -]
[2023-12-22 18:47:17,706: INFO: _internal: 127.0.0.1 - - [22/Dec/2023 18:47:17] "POST /predict HTTP/1.1" 200 -]
[2023-12-22 18:47:22,016: INFO: _internal: 127.0.0.1 - - [22/Dec/2023 18:47:22] "GET / HTTP/1.1" 200 -]
[2023-12-22 18:47:29,019: INFO: _internal: 127.0.0.1 - - [22/Dec/2023 18:47:29] "POST /predict HTTP/1.1" 200 -]
[2023-12-22 18:50:19,659: INFO: _internal: 127.0.0.1 - - [22/Dec/2023 18:50:19] "GET / HTTP/1.1" 200 -]
[2023-12-22 18:50:39,338: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.0.102:8080]
[2023-12-22 18:50:39,338: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2023-12-22 18:54:59,543: INFO: _internal: 127.0.0.1 - - [22/Dec/2023 18:54:59] "GET / HTTP/1.1" 200 -]
[2023-12-22 18:57:51,274: INFO: _internal: 127.0.0.1 - - [22/Dec/2023 18:57:51] "POST /predict HTTP/1.1" 200 -]
[2023-12-22 19:23:33,529: INFO: stage_03_model_training: *******************]
[2023-12-22 19:23:33,529: INFO: stage_03_model_training: >>>>>> stage Training started <<<<<<]
[2023-12-22 19:23:33,535: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-22 19:23:33,536: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-22 19:23:33,537: INFO: common: created directory at: artifacts]
[2023-12-22 19:23:33,537: INFO: common: created directory at: artifacts\training]
[2023-12-22 19:26:50,414: INFO: stage_03_model_training: >>>>>> stage Training completed <<<<<<

x==========x]
[2023-12-22 19:26:58,102: INFO: stage_04_model_evaluation: *******************]
[2023-12-22 19:26:58,102: INFO: stage_04_model_evaluation: >>>>>> stage Evaluation stage started <<<<<<]
[2023-12-22 19:26:58,104: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-22 19:26:58,105: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-22 19:26:58,105: INFO: common: created directory at: artifacts]
[2023-12-22 19:27:10,155: INFO: common: json file saved at: scores.json]
[2023-12-22 19:27:10,155: INFO: common: json file saved at: scores.json]
[2023-12-22 19:27:10,155: INFO: stage_04_model_evaluation: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2023-12-22 19:27:10,155: INFO: stage_04_model_evaluation: *******************]
[2023-12-22 19:27:10,156: INFO: stage_04_model_evaluation: >>>>>> stage Evaluation stage started <<<<<<]
[2023-12-22 19:27:10,158: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-22 19:27:10,160: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-22 19:27:10,162: INFO: common: created directory at: artifacts]
[2023-12-22 19:27:22,236: INFO: common: json file saved at: scores.json]
[2023-12-22 19:27:22,237: INFO: common: json file saved at: scores.json]
[2023-12-22 19:27:22,237: INFO: stage_04_model_evaluation: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2023-12-22 19:29:25,061: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.0.102:8080]
[2023-12-22 19:29:25,062: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2023-12-22 19:32:23,425: INFO: _internal: 127.0.0.1 - - [22/Dec/2023 19:32:23] "GET / HTTP/1.1" 200 -]
[2023-12-22 19:32:29,397: INFO: _internal: 127.0.0.1 - - [22/Dec/2023 19:32:29] "POST /predict HTTP/1.1" 200 -]
[2023-12-22 19:33:00,771: INFO: _internal: 127.0.0.1 - - [22/Dec/2023 19:33:00] "POST /predict HTTP/1.1" 200 -]
[2023-12-22 19:33:08,450: INFO: _internal: 127.0.0.1 - - [22/Dec/2023 19:33:08] "POST /predict HTTP/1.1" 200 -]
[2023-12-22 19:42:05,994: INFO: stage_02_prepare_base_model: >>>>>> stage Prepare Base Model started <<<<<<]
[2023-12-22 19:42:05,996: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-22 19:42:05,997: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-22 19:42:05,997: INFO: common: created directory at: artifacts]
[2023-12-22 19:42:05,998: INFO: common: created directory at: artifacts/prepare_base_model]
[2023-12-22 19:42:06,389: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2023-12-22 19:42:06,548: INFO: stage_02_prepare_base_model: >>>>>> stage Prepare Base Model completed <<<<<<

x==========x]
[2023-12-22 19:42:12,799: INFO: stage_03_model_training: *******************]
[2023-12-22 19:42:12,799: INFO: stage_03_model_training: >>>>>> stage Training started <<<<<<]
[2023-12-22 19:42:12,801: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-22 19:42:12,802: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-22 19:42:12,802: INFO: common: created directory at: artifacts]
[2023-12-22 19:42:12,802: INFO: common: created directory at: artifacts\training]
[2023-12-22 19:45:18,486: INFO: stage_03_model_training: >>>>>> stage Training completed <<<<<<

x==========x]
[2023-12-22 19:45:25,909: INFO: stage_04_model_evaluation: *******************]
[2023-12-22 19:45:25,910: INFO: stage_04_model_evaluation: >>>>>> stage Evaluation stage started <<<<<<]
[2023-12-22 19:45:25,911: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-22 19:45:25,912: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-22 19:45:25,913: INFO: common: created directory at: artifacts]
[2023-12-22 19:45:38,274: INFO: common: json file saved at: scores.json]
[2023-12-22 19:45:38,275: INFO: common: json file saved at: scores.json]
[2023-12-22 19:45:38,275: INFO: stage_04_model_evaluation: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2023-12-22 19:45:38,275: INFO: stage_04_model_evaluation: *******************]
[2023-12-22 19:45:38,275: INFO: stage_04_model_evaluation: >>>>>> stage Evaluation stage started <<<<<<]
[2023-12-22 19:45:38,277: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-22 19:45:38,278: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-22 19:45:38,279: INFO: common: created directory at: artifacts]
[2023-12-22 19:45:50,551: INFO: common: json file saved at: scores.json]
[2023-12-22 19:45:50,552: INFO: common: json file saved at: scores.json]
[2023-12-22 19:45:50,552: INFO: stage_04_model_evaluation: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2023-12-22 20:00:35,496: INFO: stage_02_prepare_base_model: >>>>>> stage Prepare Base Model started <<<<<<]
[2023-12-22 20:00:35,498: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-22 20:00:35,499: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-22 20:00:35,499: INFO: common: created directory at: artifacts]
[2023-12-22 20:00:35,500: INFO: common: created directory at: artifacts/prepare_base_model]
[2023-12-22 20:00:35,947: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2023-12-22 20:00:36,104: INFO: stage_02_prepare_base_model: >>>>>> stage Prepare Base Model completed <<<<<<

x==========x]
[2023-12-22 20:00:42,395: INFO: stage_03_model_training: *******************]
[2023-12-22 20:00:42,395: INFO: stage_03_model_training: >>>>>> stage Training started <<<<<<]
[2023-12-22 20:00:42,397: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-22 20:00:42,398: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-22 20:00:42,398: INFO: common: created directory at: artifacts]
[2023-12-22 20:00:42,398: INFO: common: created directory at: artifacts\training]
[2023-12-22 20:03:49,582: INFO: stage_03_model_training: >>>>>> stage Training completed <<<<<<

x==========x]
[2023-12-22 20:03:57,333: INFO: stage_04_model_evaluation: *******************]
[2023-12-22 20:03:57,333: INFO: stage_04_model_evaluation: >>>>>> stage Evaluation stage started <<<<<<]
[2023-12-22 20:03:57,335: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-22 20:03:57,336: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-22 20:03:57,337: INFO: common: created directory at: artifacts]
[2023-12-22 20:04:09,465: INFO: common: json file saved at: scores.json]
[2023-12-22 20:04:09,466: INFO: common: json file saved at: scores.json]
[2023-12-22 20:04:09,466: INFO: stage_04_model_evaluation: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2023-12-22 20:04:09,466: INFO: stage_04_model_evaluation: *******************]
[2023-12-22 20:04:09,466: INFO: stage_04_model_evaluation: >>>>>> stage Evaluation stage started <<<<<<]
[2023-12-22 20:04:09,468: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-22 20:04:09,469: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-22 20:04:09,470: INFO: common: created directory at: artifacts]
[2023-12-22 20:04:22,309: INFO: common: json file saved at: scores.json]
[2023-12-22 20:04:22,309: INFO: common: json file saved at: scores.json]
[2023-12-22 20:04:22,310: INFO: stage_04_model_evaluation: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2023-12-22 20:05:03,778: INFO: stage_03_model_training: *******************]
[2023-12-22 20:05:03,779: INFO: stage_03_model_training: >>>>>> stage Training started <<<<<<]
[2023-12-22 20:05:03,780: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-22 20:05:03,781: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-22 20:05:03,781: INFO: common: created directory at: artifacts]
[2023-12-22 20:05:03,782: INFO: common: created directory at: artifacts\training]
[2023-12-22 20:11:12,335: INFO: stage_03_model_training: >>>>>> stage Training completed <<<<<<

x==========x]
[2023-12-22 20:11:20,009: INFO: stage_04_model_evaluation: *******************]
[2023-12-22 20:11:20,009: INFO: stage_04_model_evaluation: >>>>>> stage Evaluation stage started <<<<<<]
[2023-12-22 20:11:20,010: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-22 20:11:20,011: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-22 20:11:20,012: INFO: common: created directory at: artifacts]
[2023-12-22 20:11:31,978: INFO: common: json file saved at: scores.json]
[2023-12-22 20:11:31,979: INFO: common: json file saved at: scores.json]
[2023-12-22 20:11:31,979: INFO: stage_04_model_evaluation: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2023-12-22 20:11:31,979: INFO: stage_04_model_evaluation: *******************]
[2023-12-22 20:11:31,979: INFO: stage_04_model_evaluation: >>>>>> stage Evaluation stage started <<<<<<]
[2023-12-22 20:11:31,981: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-22 20:11:31,982: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-22 20:11:31,982: INFO: common: created directory at: artifacts]
[2023-12-22 20:11:44,128: INFO: common: json file saved at: scores.json]
[2023-12-22 20:11:44,129: INFO: common: json file saved at: scores.json]
[2023-12-22 20:11:44,129: INFO: stage_04_model_evaluation: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2023-12-22 20:13:14,125: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.0.102:8080]
[2023-12-22 20:13:14,125: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2023-12-22 20:30:20,291: INFO: _internal: 127.0.0.1 - - [22/Dec/2023 20:30:20] "GET / HTTP/1.1" 200 -]
[2023-12-22 20:30:30,452: INFO: _internal: 127.0.0.1 - - [22/Dec/2023 20:30:30] "POST /predict HTTP/1.1" 200 -]
[2023-12-22 20:44:32,538: INFO: _internal: 127.0.0.1 - - [22/Dec/2023 20:44:32] "POST /predict HTTP/1.1" 200 -]
[2023-12-22 20:44:39,528: INFO: _internal: 127.0.0.1 - - [22/Dec/2023 20:44:39] "POST /predict HTTP/1.1" 200 -]
[2023-12-22 20:45:08,828: INFO: _internal: 127.0.0.1 - - [22/Dec/2023 20:45:08] "POST /predict HTTP/1.1" 200 -]
[2023-12-22 20:45:23,935: WARNING: polymorphic_function: 5 out of the last 5 calls to <function Model.make_predict_function.<locals>.predict_function at 0x0000022C6DAB20C0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.]
[2023-12-22 20:45:23,940: INFO: _internal: 127.0.0.1 - - [22/Dec/2023 20:45:23] "POST /predict HTTP/1.1" 200 -]
[2023-12-22 20:52:19,540: INFO: _internal: 127.0.0.1 - - [22/Dec/2023 20:52:19] "GET / HTTP/1.1" 200 -]
[2023-12-22 20:52:25,395: WARNING: polymorphic_function: 6 out of the last 6 calls to <function Model.make_predict_function.<locals>.predict_function at 0x0000022C6DAB1580> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.]
[2023-12-22 20:52:25,400: INFO: _internal: 127.0.0.1 - - [22/Dec/2023 20:52:25] "POST /predict HTTP/1.1" 200 -]
[2023-12-22 20:55:56,045: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.0.102:8080]
[2023-12-22 20:55:56,045: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2023-12-22 20:56:37,841: INFO: _internal: 127.0.0.1 - - [22/Dec/2023 20:56:37] "GET / HTTP/1.1" 200 -]
[2023-12-22 20:56:54,175: INFO: _internal: 127.0.0.1 - - [22/Dec/2023 20:56:54] "POST /predict HTTP/1.1" 200 -]
[2023-12-22 20:59:21,518: INFO: _internal: 127.0.0.1 - - [22/Dec/2023 20:59:21] "GET / HTTP/1.1" 200 -]
[2023-12-22 20:59:32,758: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.0.102:8080]
[2023-12-22 20:59:32,758: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2023-12-22 20:59:37,926: INFO: _internal: 127.0.0.1 - - [22/Dec/2023 20:59:37] "GET / HTTP/1.1" 200 -]
[2023-12-22 20:59:42,660: INFO: _internal: 127.0.0.1 - - [22/Dec/2023 20:59:42] "POST /predict HTTP/1.1" 200 -]
[2023-12-22 21:01:08,718: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.0.102:8080]
[2023-12-22 21:01:08,719: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2023-12-22 21:01:18,968: INFO: _internal: 127.0.0.1 - - [22/Dec/2023 21:01:18] "GET / HTTP/1.1" 200 -]
[2023-12-22 21:01:26,944: INFO: _internal: 127.0.0.1 - - [22/Dec/2023 21:01:26] "POST /predict HTTP/1.1" 200 -]
[2023-12-22 21:01:38,025: INFO: _internal: 127.0.0.1 - - [22/Dec/2023 21:01:38] "POST /predict HTTP/1.1" 200 -]
[2023-12-22 21:04:00,084: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.0.102:8080]
[2023-12-22 21:04:00,085: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2023-12-22 21:05:47,272: INFO: _internal: 127.0.0.1 - - [22/Dec/2023 21:05:47] "GET / HTTP/1.1" 200 -]
[2023-12-22 21:05:51,536: INFO: _internal: 127.0.0.1 - - [22/Dec/2023 21:05:51] "POST /predict HTTP/1.1" 200 -]
[2023-12-22 21:06:19,374: INFO: _internal: 127.0.0.1 - - [22/Dec/2023 21:06:19] "POST /predict HTTP/1.1" 200 -]
[2023-12-22 21:06:42,748: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.0.102:8080]
[2023-12-22 21:06:42,748: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2023-12-22 21:06:50,329: INFO: _internal: 127.0.0.1 - - [22/Dec/2023 21:06:50] "GET / HTTP/1.1" 200 -]
[2023-12-22 21:06:56,860: INFO: _internal: 127.0.0.1 - - [22/Dec/2023 21:06:56] "POST /predict HTTP/1.1" 200 -]
[2023-12-22 21:10:57,636: INFO: _internal: 127.0.0.1 - - [22/Dec/2023 21:10:57] "POST /predict HTTP/1.1" 200 -]
[2023-12-22 21:15:55,218: INFO: _internal: 127.0.0.1 - - [22/Dec/2023 21:15:55] "GET / HTTP/1.1" 200 -]
[2023-12-22 21:16:12,271: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.0.102:8080]
[2023-12-22 21:16:12,271: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2023-12-22 21:16:34,854: INFO: _internal: 127.0.0.1 - - [22/Dec/2023 21:16:34] "GET / HTTP/1.1" 200 -]
[2023-12-22 21:16:39,899: INFO: _internal: 127.0.0.1 - - [22/Dec/2023 21:16:39] "POST /predict HTTP/1.1" 200 -]
[2023-12-22 21:23:08,357: INFO: _internal: 127.0.0.1 - - [22/Dec/2023 21:23:08] "GET / HTTP/1.1" 200 -]
[2023-12-22 21:23:21,166: INFO: _internal: 127.0.0.1 - - [22/Dec/2023 21:23:21] "POST /predict HTTP/1.1" 200 -]
[2023-12-22 21:23:47,098: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.0.102:8080]
[2023-12-22 21:23:47,099: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2023-12-22 21:23:51,262: INFO: _internal: 127.0.0.1 - - [22/Dec/2023 21:23:51] "GET / HTTP/1.1" 200 -]
[2023-12-22 21:23:53,847: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\Rehan Shaikh\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rehan Shaikh\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rehan Shaikh\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rehan Shaikh\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rehan Shaikh\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rehan Shaikh\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
                         ^^^^^^^^^^^^^^^^^^
  File "E:\mlops\Kidney-Disease-Classification-DL-Project\app.py", line 40, in predictRoute
    result = clApp.classifier.predict()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\mlops\Kidney-Disease-Classification-DL-Project\src\cnnClassifier\pipeline\predict.py", line 21, in predict
    image_name = image.load_img(imagename, target_size = (224,224))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rehan Shaikh\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\utils\image_utils.py", line 423, in load_img
    img = pil_image.open(io.BytesIO(f.read()))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rehan Shaikh\AppData\Local\Programs\Python\Python311\Lib\site-packages\PIL\Image.py", line 3305, in open
    raise UnidentifiedImageError(msg)
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x000001F521F9A840>
[2023-12-22 21:23:53,903: INFO: _internal: 127.0.0.1 - - [22/Dec/2023 21:23:53] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2023-12-22 21:23:55,417: INFO: _internal: 127.0.0.1 - - [22/Dec/2023 21:23:55] "GET / HTTP/1.1" 200 -]
[2023-12-22 21:24:02,565: INFO: _internal: 127.0.0.1 - - [22/Dec/2023 21:24:02] "POST /predict HTTP/1.1" 200 -]
